config/routes.rb
Store::Application.routes.draw do
  devise_for :users
  resources :products do
    resources :reviews
  end
  root :to => "products#index"
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :price, :discontinued_at
  has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :content, :rating
  belongs_to :product
  scope :rating, proc { |rating| where(:rating => rating) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/products_controller.rb
class ProductsController < InheritedResources::Base
  before_filter :authenticate_user! 
  respond_to :html, :xml, :json
  has_scope :limit, :default => 8
  
  def create
    create! { products_path }
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < InheritedResources::Base
  belongs_to :product
  actions :index, :new, :create
  has_scope :rating
  
  def create
    create! { collection_url }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options! 
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end
  
  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) || "Untitled" %></title>
    <%= stylesheet_link_tag :application %>
    <%= javascript_include_tag :application %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <div id="user_nav">
        <% if user_signed_in? %>
        Signed in as <%= current_user.email %>. Not you?
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
        <% else %>
        <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/products/edit.html.erb
<% title "Edit Product" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @product %> |
  <%= link_to "View All", products_path %>
</p>

app/views/products/index.html.erb
<% title "Products" %>

<% for product in @products %>
  <div class="product">
    <h2><%= product.name %></h2>
    <div class="details">
      Price: <%= number_to_currency(product.price) %> |
      <%= link_to "Read Reviews", product_reviews_path(product) %>
    </div>
    <p id="pdf_link">
  <%= link_to "Download Invoice (PDF)", product_path(product, :format => "pdf") %>
</p>

  </div>
<% end %>

<p><%= link_to "New Product", new_product_path %></p>

app/views/products/new.html.erb
<% title "New Product" %>

<%= render 'form' %>

<p><%= link_to "Back to List", products_path %></p>

app/views/products/show.html.erb
<% title "Product" %>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>
<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>
<p>
  <%= link_to "Edit", edit_product_path(@product) %> |
  <%= link_to "Destroy", @product, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", products_path %>
</p>

app/views/reviews/index.html.erb
<% title "Reviews for #{@product.name}" %>

<p><%= link_to "Back to Products", products_path %></p>

<% if @reviews.empty? %>
  <h2>No reviews yet.</h2>
<% else %>
  <% for review in @reviews %>
    <div class="review">
      <p>Rating: <%= review.rating %></p>
      <p><%= review.content %></p>
    </div>
  <% end %>
<% end %>

<p><%= link_to "Add a Review", new_product_review_path(@product) %></p>

app/views/reviews/new.html.erb
<% title "New Review for #{@product.name}" %>

<%= form_for [@product, @review] do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content, :rows => 10, :cols => 40 %>
  </p>
  <p>
    <%= f.label :rating %><br />
    <%= f.select :rating, 1..5 %>
  </p>
  <p><%= f.submit %></p>
<% end %>


<p><%= link_to "Back to Reviews", product_reviews_path(@product) %></p>